### ISSUE TITLE
load blocked when key with authentication

### ISSUE THREAD

**Issue by eraigosa** [fglaeser/Extensions.Configuration.Zookeeper#2]
hi, when you have a key created with authentication under the rootPath, for example 
```
List<ACL> mode = ZooDefs.Ids.CREATOR_ALL_ACL;
zk.addAuthInfo("digest", "app1:app123".GetBytes());
zk.createAsync(schema, null, mode, CreateMode.PERSISTENT)
```
on "IConfiguration.build()" it gets blocked because it is connected to ZK but getting an error when trying to get the data... so it tries again and again and again... 

so, 2 errors, first, it is not possible to set the authentication to the ZK client.
second, because of the internal hidden of the exception, there is never a notification or any kind of message, I'd remove some try-catch so the exceptions can be propagated properly.

I'll try to find some time to solve it in the near future, btw thanks for sharing the code.

--------
```
this is the test method I did
[TestMethod()]
        public void CreateNGetConfigurationTestManualDELETE()
        {
            //Get Zookeeper Server Info
            IConfigurationBuilder configBuilder = new ConfigurationBuilder().SetBasePath(Path.Combine(AppContext.BaseDirectory))
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            IConfigurationRoot appSettingsFileConfig = configBuilder.Build();

            string connectionString = appSettingsFileConfig["Zookeeper:ConnectionString"];

            //https://github.com/rubms/DotNet.MultisourceConfiguration.Zookeeper
            ZooKeeper _zooKeeper = ZooKeeperUtil.CreateManualClient(connectionString);

            string zooKeeperRootPath = ZooKeeperUtil.GetRootPath(appSettingsFileConfig);

            var waiter = _zooKeeper.LoadDataAsync(zooKeeperRootPath);
            waiter.Wait();
            var DATA = waiter.Result;
            Assert.IsTrue(DATA.ContainsKey("validAnyKeyForTest"));
        }
```

**Comment by fglaeser** [comment]
Hi, first of all, thanks for sharing. I didn't check deeply, but what if I add a method for the authentication in the Zookeeper Option class to set the auth values. e.g

```
builder.AddZookeeper(option =>
{
    option.ConnectionString = "localhost:2181";
    option.ConnectionTimeout = 10000;
    option.RootPath = "/AccountApp";
    option.SessionTimeout = 3000;
    // HERE.......
    option.AddAuthInfo("digest", " app1:app123".GetBytes());
});

```
And then in the ctor of ZookeeperConfigurationProvider we do the addAuthInfo call.

```
public ZookeeperConfigurationProvider(ZookeeperOption option, IZooKeeperFactory zookeeperFactory)
{
        _option = option;
        _zooKeeperFactory = zookeeperFactory;
        _zooKeeper = _zooKeeperFactory.CreateZooKeeper(_option.ConnectionString, 
               _option.SessionTimeout, out _watcher);
         // HERE......
        _zooKeeper.addAuthInfo(_option.Authentication.Schema, _option.Authentication.Auth);
        _watcher.StateChanged += OnStateChanged;
        _watcher.NodeChanged += OnNodeChanged;
        _connectedEvent = new ManualResetEvent(false);
        _loadCompletedEvent = new AutoResetEvent(false);
}

```
Could the solution fits you? Are you able to test this? If not, I will check that ASAP and release a new version.

Thanks again!!

**Comment by eraigosa** [comment]
it seems ok, you might need an if condition to see if the schema and auth were set.
I recommend you before solving that specific bug, to do a test without any modification and try to solve first the hiding-exception issue.
thanks... 
PS: right now I'm really busy but I hope next week I can work on the issues (either to solve or to test)
