### ISSUE TITLE
watcher error on key added or deleted

### ISSUE THREAD

**Issue by eraigosa** [fglaeser/Extensions.Configuration.Zookeeper#5]
I have a web app (but it can be done easily with a console app)
steeps to reproduce.

0. run the web app. 
it loads all the ZK keys in the IConfiguration 
0.1. **edit** an existing key in ZK
it updates the value for the key in your Config
read again and show your modified key. **it works**
----
now the **ERRORs =>**

1. run the web app. 
it loads all the ZK keys in the IConfiguration 
1.1 **Create** a new key in ZK
the web app **crashes**.

2 run the web app. 
it loads all the ZK keys in the IConfiguration 
2.1 **Create** a new key in ZK
the web app **crashes**.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DotNet.Extensions.Configuration.Zookeeper
  StackTrace:
   at DotNet.Extensions.Configuration.Zookeeper.ZookeeperConfigurationProvider.<OnNodeChildrenChanged>d__18.MoveNext() in C:\Users\eraigosa\Source\Repos\Extensions.Configuration.Zookeeper\src\DotNet.Extensions.Configuration.Zookeeper\ZookeeperConfigurationProvider.cs:line 207
![image](https://user-images.githubusercontent.com/945546/82354975-911b8000-99cf-11ea-8012-5e4e4d325766.png)

I presume it would be better to execute a different function for each type of event
![image](https://user-images.githubusercontent.com/945546/82355080-bc05d400-99cf-11ea-9c54-58e8be7a6999.png)

Note: in my use-cases, I don't need to manage the new/delete key, just the edition... and I think it is very likely you don't need to care about that either, so another option is just to ignore the NodeDeleted and NodeChildrenChanged as NodeCreated is been ignored.

**Comment by fglaeser** [comment]
I think I found the problem. I've just push some changes to the repo. Could you test it against your application?  Thanks.

**Comment by eraigosa** [comment]
delete works... new-key is not working but at least is not throwing an error... for my use-cases that is perfect... let me know if you want me to test a new version of the new-key.
note: it "doesn't work" is because when I add a new key it doesn't recognize it so the new value is never added to the IConfig, but I think that is ok. (I don't know if you want a new key to be part of the IConfig)

**Comment by eraigosa** [comment]
can I ask you what is the procedure you are using to publish to NuGet? (I have done that to my on-prem nugget manually but maybe you have some automatic tool).. (sorry I used this issue to ask that, I don't want to start a completely new thread for something so basic)... with just a name is enough for me, I'll read the rest

**Comment by fglaeser** [comment]
> delete works... new-key is not working but at least is not throwing an error... for my use-cases that is perfect... let me know if you want me to test a new version of the new-key.
> note: it "doesn't work" is because when I add a new key it doesn't recognize it so the new value is never added to the IConfig, but I think that is ok. (I don't know if you want a new key to be part of the IConfig)

Could you check again? I've tested with a second level node the first time and it was OK, but with one first level node there was a problem. It is fix now. It would be very helpful if you could test it againts your application in order to close the issue. In the mean time I will add more unit test for that.
Thanks

**Comment by fglaeser** [comment]
> can I ask you what is the procedure you are using to publish to NuGet? (I have done that to my on-prem nugget manually but maybe you have some automatic tool).. (sorry I used this issue to ask that, I don't want to start a completely new thread for something so basic)... with just a name is enough for me, I'll read the rest

I'm currently doing it manually. As you can see, I've just replaced Travis CI with GitHub Actions. I want to use Github Action also to pack and push the package.

**Comment by eraigosa** [comment]
yes, it is working properly... 
thanks :)

**Comment by eraigosa** [comment]
Hi sorry to bother you... I want to know when you have planned to add the package to Nuget, I rather to use Nugets instead of source code. if you don't plan to publish it soon I can do it my self. let me know. thanks and sorry again.

**Comment by fglaeser** [comment]
> Hi sorry to bother you... I want to know when you have planned to add the package to Nuget, I rather to use Nugets instead of source code. if you don't plan to publish it soon I can do it my self. let me know. thanks and sorry again.
I Will do it tomorrow morning.
Sorry about the delay.
Best regards.
Facundo
